version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: golang-apifull
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql